name: Build and Push Docker Image

on:
  # Uruchom automatycznie przy wypchnięciu kodu na gałąź main
  push:
    branches: [ "main" ]
  # Pozwól na ręczne uruchomienie przyciskiem z zakładki Actions
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # UWAGA: Upewnij się, że nazwa obrazu zawiera Twój login z DockerHuba!
          # Zastąp 'twoj-login' swoim prawdziwym loginem, np.: mati2002103/flask-app
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
